# Configuration for the crypto trading bot

data:
  sample_data_path: data/sample_ohlcv.csv
  symbols: ['BTC/USDT', 'ETH/USDT']
  timeframe: '5m'
  lookback: 60

models:
  model_type: 'lstm' # Can be 'lstm' or 'transformer'
  garch:
    p: 1
    q: 1
  anomaly:
    contamination: 0.05
  lstm:
    hidden_size: 64
    num_layers: 2
  transformer:
    d_model: 64
    nhead: 4
    num_encoder_layers: 2
    dim_feedforward: 256
    dropout: 0.1

training:
  batch_size: 2048
  max_epochs: 100

inference:
  models_dir: 'models'

exchange:
  name: 'binance'
  api_key: 'YOUR_API_KEY'
  secret_key: 'YOUR_SECRET_KEY'

trading:
  risk_percentage: 0.01
  stop_loss_percentage: 0.02
  take_profit_percentage: 0.04
  trailing_stop:
    enabled: true
    percentage: 0.01

telegram:
  token: 'YOUR_TELEGRAM_BOT_TOKEN'
  chat_id: 'YOUR_TELEGRAM_CHAT_ID'
